name: CI & npm publish

on:
  push:
    branches: [main]
    paths-ignore:
      - 'package.json'

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: git config --global user.name 'Triston Armstrong'
      - run: git config --global user.email 'triston95strong@gmail.com'
      - run: npm version patch -m "chore(release) %s"
      - run: git push

  build:
    needs: bump_version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci

  pre_release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create Github Release
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: 'latest'
          prerelease: true

  publish:
    needs: pre_release
    runs-on: ubuntu-latest
    steps:
      - name: Setup npm
        uses: actions/npm@v3
        with:
          registry-auth: ${{secrets.NPM_RELEASE_DEP}}
          registry-url: 'https://registry.npmjs.org'
      - name: Publishing to NPM
        run: npm publish